services:
  test_db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_recipe_app
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
    networks:
      - test_recipe_net

  test_minio:
    image: minio/minio
    command: server --console-address ":9091" /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9090:9000"   # S3 API
      - "9091:9091"   # MinIO console
    networks:
      - test_recipe_net

networks:
  test_recipe_net:
